"use strict"

let painting = [];
let palette = [];
let brushColor;
let colorOff;
let pad;
let selectedColorKey = [8,7];
let resetCheatCount = 0;
let startTime;
const animation = [];
const displayanimation = [ { time: 1797,
  k:
   { '0': 0,
     '1': 0,
     x: 0,
     y: 0,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 1876,
  k:
   { '0': 0,
     '1': 1,
     x: 0,
     y: 1,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 1921,
  k:
   { '0': 0,
     '1': 2,
     x: 0,
     y: 2,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 1961,
  k:
   { '0': 0,
     '1': 3,
     x: 0,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 1994,
  k:
   { '0': 0,
     '1': 4,
     x: 0,
     y: 4,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 2027,
  k:
   { '0': 0,
     '1': 5,
     x: 0,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 2069,
  k:
   { '0': 0,
     '1': 6,
     x: 0,
     y: 6,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 2125,
  k:
   { '0': 0,
     '1': 7,
     x: 0,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 2742,
  k:
   { '0': 1,
     '1': 0,
     x: 1,
     y: 0,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 2817,
  k:
   { '0': 1,
     '1': 1,
     x: 1,
     y: 1,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 2869,
  k:
   { '0': 1,
     '1': 2,
     x: 1,
     y: 2,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 2906,
  k:
   { '0': 1,
     '1': 3,
     x: 1,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 2941,
  k:
   { '0': 1,
     '1': 4,
     x: 1,
     y: 4,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 2978,
  k:
   { '0': 1,
     '1': 5,
     x: 1,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 3018,
  k:
   { '0': 1,
     '1': 6,
     x: 1,
     y: 6,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 3068,
  k:
   { '0': 1,
     '1': 7,
     x: 1,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 3135,
  k:
   { '0': 1,
     '1': 7,
     x: 1,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 3727,
  k:
   { '0': 2,
     '1': 0,
     x: 2,
     y: 0,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 3786,
  k:
   { '0': 2,
     '1': 0,
     x: 2,
     y: 0,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 3802,
  k:
   { '0': 2,
     '1': 1,
     x: 2,
     y: 1,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 3851,
  k:
   { '0': 2,
     '1': 2,
     x: 2,
     y: 2,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 3892,
  k:
   { '0': 2,
     '1': 3,
     x: 2,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 3930,
  k:
   { '0': 2,
     '1': 4,
     x: 2,
     y: 4,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 3972,
  k:
   { '0': 2,
     '1': 5,
     x: 2,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 4015,
  k:
   { '0': 2,
     '1': 6,
     x: 2,
     y: 6,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 4067,
  k:
   { '0': 2,
     '1': 7,
     x: 2,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 4766,
  k:
   { '0': 3,
     '1': 0,
     x: 3,
     y: 0,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 4828,
  k:
   { '0': 3,
     '1': 1,
     x: 3,
     y: 1,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 4867,
  k:
   { '0': 3,
     '1': 2,
     x: 3,
     y: 2,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 4902,
  k:
   { '0': 3,
     '1': 3,
     x: 3,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 4933,
  k:
   { '0': 3,
     '1': 4,
     x: 3,
     y: 4,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 4966,
  k:
   { '0': 3,
     '1': 5,
     x: 3,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 5003,
  k:
   { '0': 3,
     '1': 6,
     x: 3,
     y: 6,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 5045,
  k:
   { '0': 3,
     '1': 7,
     x: 3,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 5703,
  k:
   { '0': 4,
     '1': 0,
     x: 4,
     y: 0,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 5782,
  k:
   { '0': 4,
     '1': 0,
     x: 4,
     y: 0,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 5804,
  k:
   { '0': 4,
     '1': 1,
     x: 4,
     y: 1,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 5854,
  k:
   { '0': 4,
     '1': 2,
     x: 4,
     y: 2,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 5894,
  k:
   { '0': 4,
     '1': 3,
     x: 4,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 5931,
  k:
   { '0': 4,
     '1': 4,
     x: 4,
     y: 4,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 5968,
  k:
   { '0': 4,
     '1': 5,
     x: 4,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 6009,
  k:
   { '0': 4,
     '1': 6,
     x: 4,
     y: 6,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 6064,
  k:
   { '0': 4,
     '1': 7,
     x: 4,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'red' },
{ time: 6757,
  k:
   { '0': 5,
     '1': 0,
     x: 5,
     y: 0,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 6833,
  k:
   { '0': 5,
     '1': 0,
     x: 5,
     y: 0,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 6849,
  k:
   { '0': 5,
     '1': 1,
     x: 5,
     y: 1,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 6896,
  k:
   { '0': 5,
     '1': 2,
     x: 5,
     y: 2,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 6942,
  k:
   { '0': 5,
     '1': 3,
     x: 5,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 6979,
  k:
   { '0': 5,
     '1': 4,
     x: 5,
     y: 4,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 7015,
  k:
   { '0': 5,
     '1': 5,
     x: 5,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 7056,
  k:
   { '0': 5,
     '1': 6,
     x: 5,
     y: 6,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 7099,
  k:
   { '0': 5,
     '1': 7,
     x: 5,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 7754,
  k:
   { '0': 6,
     '1': 0,
     x: 6,
     y: 0,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 7825,
  k:
   { '0': 6,
     '1': 1,
     x: 6,
     y: 1,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 7875,
  k:
   { '0': 6,
     '1': 2,
     x: 6,
     y: 2,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 7917,
  k:
   { '0': 6,
     '1': 3,
     x: 6,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 7956,
  k:
   { '0': 6,
     '1': 4,
     x: 6,
     y: 4,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 7995,
  k:
   { '0': 6,
     '1': 5,
     x: 6,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 8043,
  k:
   { '0': 6,
     '1': 6,
     x: 6,
     y: 6,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 8111,
  k:
   { '0': 6,
     '1': 7,
     x: 6,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 8747,
  k:
   { '0': 7,
     '1': 0,
     x: 7,
     y: 0,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 8831,
  k:
   { '0': 7,
     '1': 1,
     x: 7,
     y: 1,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 8885,
  k:
   { '0': 7,
     '1': 2,
     x: 7,
     y: 2,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 8922,
  k:
   { '0': 7,
     '1': 3,
     x: 7,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 8953,
  k:
   { '0': 7,
     '1': 4,
     x: 7,
     y: 4,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 8982,
  k:
   { '0': 7,
     '1': 5,
     x: 7,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 9016,
  k:
   { '0': 7,
     '1': 6,
     x: 7,
     y: 6,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 9064,
  k:
   { '0': 7,
     '1': 7,
     x: 7,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 9122,
  k:
   { '0': 7,
     '1': 7,
     x: 7,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'green' },
{ time: 9805,
  k:
   { '0': 7,
     '1': 7,
     x: 7,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 9898,
  k:
   { '0': 6,
     '1': 7,
     x: 6,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 9956,
  k:
   { '0': 5,
     '1': 7,
     x: 5,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 10002,
  k:
   { '0': 4,
     '1': 7,
     x: 4,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 10046,
  k:
   { '0': 3,
     '1': 7,
     x: 3,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 10087,
  k:
   { '0': 2,
     '1': 7,
     x: 2,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 10133,
  k:
   { '0': 1,
     '1': 7,
     x: 1,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 10197,
  k:
   { '0': 0,
     '1': 7,
     x: 0,
     y: 7,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 10932,
  k:
   { '0': 7,
     '1': 5,
     x: 7,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 11036,
  k:
   { '0': 6,
     '1': 5,
     x: 6,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 11097,
  k:
   { '0': 6,
     '1': 5,
     x: 6,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 11117,
  k:
   { '0': 5,
     '1': 5,
     x: 5,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 11178,
  k:
   { '0': 4,
     '1': 5,
     x: 4,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 11199,
  k:
   { '0': 4,
     '1': 6,
     x: 4,
     y: 6,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 11222,
  k:
   { '0': 3,
     '1': 5,
     x: 3,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 11264,
  k:
   { '0': 2,
     '1': 5,
     x: 2,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 11311,
  k:
   { '0': 1,
     '1': 5,
     x: 1,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 11384,
  k:
   { '0': 0,
     '1': 5,
     x: 0,
     y: 5,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 11930,
  k:
   { '0': 7,
     '1': 3,
     x: 7,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 11992,
  k:
   { '0': 7,
     '1': 3,
     x: 7,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 12014,
  k:
   { '0': 6,
     '1': 3,
     x: 6,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 12073,
  k:
   { '0': 5,
     '1': 3,
     x: 5,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 12119,
  k:
   { '0': 4,
     '1': 3,
     x: 4,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 12160,
  k:
   { '0': 3,
     '1': 3,
     x: 3,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 12207,
  k:
   { '0': 2,
     '1': 3,
     x: 2,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 12263,
  k:
   { '0': 1,
     '1': 3,
     x: 1,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 12329,
  k:
   { '0': 0,
     '1': 3,
     x: 0,
     y: 3,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 12960,
  k:
   { '0': 7,
     '1': 1,
     x: 7,
     y: 1,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 13037,
  k:
   { '0': 6,
     '1': 1,
     x: 6,
     y: 1,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' },
{ time: 13085,
  k:
   { '0': 5,
     '1': 1,
     x: 5,
     y: 1,
     pressed: true,
     id: Symbol(),
     length: 2 },
  color: 'amber' }];


const freepaint = {
  init: function(utils, socketB) {
    socketB.on('Freepaint update', (sequence) => freepaint.paintAnimation(sequence.sequence));
    startTime = new Date();
    pad = utils;
    brushColor = pad.colors.red;
    colorOff = pad.colors.off;
    palette = [
      [pad.colors.red.low, [8, 0]],
      [pad.colors.red.full, [8, 1]],
      [pad.colors.green.low, [8, 2]],
      [pad.colors.green.full, [8, 3]],
      [pad.colors.amber.low, [8, 4]],
      [pad.colors.amber.full, [8, 5]],
      [pad.colors.off, [8, 6]]
      // [pad.colors.yellow.low, [8, 6]],
      // [pad.colors.yellow.full, [8, 7]]
    ];
    freepaint.paintPalette();
    // freepaint.paintAnimation(displayanimation);
  },
  paintPalette: function() {
    palette.forEach(function(item) {
      pad.paint(item[0], item[1]);
    });
    pad.paint(brushColor, selectedColorKey);
  },
  paintAnimation: function(chosenAnimation) {
    console.log(chosenAnimation);
    chosenAnimation.forEach(function(item) {
      console.log(item);
      setTimeout(() => {
        console.log('paint');
        pad.paint(pad.colors[item.color], { 0: item.x, 1: item.y, x: item.x, y: item.y, isPressed: true});
      }, item.time);
    });
  },
  padFunction: function(k, isPressed) {
    if (isPressed) {
      if (pad.isRightControl(k)) {
        if (pad.isRightControl(k,6)) {
          freepaint.setNewColor(k); 
          // freepaint.log(); // logs the painting coordinates
          console.log(animation);
          freepaint.resetCheat(); // three times in a row cleans the board
        } else if (!pad.isRightControl(k,7)) {
          freepaint.setNewColor(k);
        }
      } else if (!pad.isTopControl(k)) {

        /* https://stackoverflow.com/a/41633001 */
        /////////
        const pressedTime = new Date();
        let timeDiff = pressedTime - startTime; //in ms
        animation.push({
          time: timeDiff,
          k: k,
          color: brushColor._name
        });
        /////////

        freepaint.togglePaint(k);
      }
    }
  },
  setNewColor: function(k) {
    const controlIndex = palette.findIndex(function(item) {
      return item[1][0] === k[0] && item[1][1] === k[1]
    });
    brushColor = palette[controlIndex][0];
    pad.paint(brushColor, selectedColorKey);
  },
  togglePaint: function(k) {
    const foundIndex = painting.findIndex((key) => key[0][0] === k[0] && key[0][1] === k[1]);
    if (foundIndex < 0) {
      freepaint.addPaint(k);
    } else if (painting[foundIndex][1] !== brushColor) {
      freepaint.replace(k, foundIndex);
    } else {
      freepaint.removePaint(k, foundIndex);
    }
  },
  log: function() {
    console.log(painting.map(pair => [pair[0][0], pair[0][1]]));
  },
  resetCheat: function() {
    resetCheatCount++;
    if (resetCheatCount > 3) {
      resetCheatCount = 0;
      painting = [];
      pad.cleanBoard();
    }
  },
  addPaint: function(k) {
    painting.push([k, brushColor]);
    pad.paint(brushColor, k);
  },
  removePaint: function(k, index) {
    painting.splice(index, 1);
    pad.paint(colorOff, k);
  },
  replace: function(k, index) {
    freepaint.removePaint(k, index);
    freepaint.addPaint(k);
  }
}

module.exports = freepaint;